name: pomodoro
description: Pomodoro Timer.

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  flutter_local_notifications: ^0.8.0
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  screenshots: ^1.3.0
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true
