name: pomodoro
description: Super Pomodoro Timer.
repository: https://github.com/3daysapp/pomodoro/
publish_to: none

version: 0.0.11+11

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/audioplayers
  audioplayers: 6.1.1

  # https://pub.dev/packages/duration_picker
  # duration_picker: 1.2.0
  duration_picker:
    path: ../../github/duration_picker

  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: 11.4.1

  # https://pub.dev/packages/firebase_core
  firebase_core: 3.10.1

  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: 4.3.1

  # https://flutter.dev/
  flutter:
    sdk: flutter

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/flutter_udid
  # TODO(edufolly): Need to update to 4.0.0
  flutter_udid: 3.0.0

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 10.8.0

  # https://pub.dev/packages/i18next
  i18next: 0.7.3

  # https://pub.dev/packages/intl
  intl: ^0.19.0

  # https://pub.dev/packages/package_info_plus
  package_info_plus: 8.1.4

  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.5.1

  # https://pub.dev/packages/flutter_local_notifications
  # flutter_local_notifications: 2.0.0+1
  # flutter_local_notifications: 3.0.1+3

  # https://pub.dev/packages/flutter_picker
  # flutter_picker: 2.1.0

  # https://pub.dev/packages/wakelock_plus
  wakelock_plus: 1.2.10

dev_dependencies:
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: 0.14.3

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^5.0.0

  # https://flutter.dev/
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^1.3.0

  # https://pub.dev/packages/yaml
  yaml: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - l10n/
    - l10n/en-US/
