name: pomodoro
description: Super Pomodoro Timer.
repository: https://github.com/3daysapp/pomodoro/

version: 0.0.7+7

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/duration_picker
  duration_picker: 1.2.0

  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: 11.3.0

  # https://pub.dev/packages/firebase_core
  firebase_core: 3.4.0

  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: 4.1.0

  # https://flutter.dev/
  flutter:
    sdk: flutter

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/flutter_udid
  flutter_udid: 3.0.0

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 10.7.0

  # https://pub.dev/packages/i18next
  i18next: ^0.7.3

  # https://pub.dev/packages/intl
  intl: ^0.19.0

  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.0.2

  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.3.2

  # https://pub.dev/packages/flutter_local_notifications
  # flutter_local_notifications: 2.0.0+1
  # flutter_local_notifications: 3.0.1+3

  # https://pub.dev/packages/flutter_picker
  # flutter_picker: 1.1.5

  # https://pub.dev/packages/firebase_core
  # firebase_core: 0.5.2

  # https://pub.dev/packages/firebase_analytics
  # firebase_analytics: 6.2.0

  # https://pub.dev/packages/firebase_crashlytics
  # firebase_crashlytics: 0.2.3

  # https://pub.dev/packages/wakelock_plus
  wakelock_plus: 1.2.8

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0

  # https://flutter.dev/
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^1.2.0

  # https://pub.dev/packages/yaml
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - l10n/
    - l10n/en-US/
