name: pomodoro
description: Super Pomodoro Timer.

version: 0.0.6+6

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 8.10.0
  # https://pub.dev/packages/intl
  intl: 0.16.1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.12
  # https://pub.dev/packages/package_info
  package_info: 0.4.3
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: 2.0.0+1
  # https://pub.dev/packages/flutter_picker
  flutter_picker: 1.1.5
  # https://pub.dev/packages/firebase_core
  firebase_core: 0.5.0+1
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: 6.0.2
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: 0.2.1+1
  # https://pub.dev/packages/flutter_udid
  flutter_udid: 1.0.1
  # https://pub.dev/packages/wakelock
  wakelock: 0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/