name: pomodoro
description: Super Pomodoro Timer.

version: 0.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: 0.1.3
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.7
  # https://pub.dev/packages/package_info
  package_info: 0.4.0+17
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: 1.4.1
  # https://pub.dev/packages/flutter_picker
  flutter_picker: 1.1.3
  # https://pub.dev/packages/firebase_core
  firebase_core: 0.4.4+3
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: 5.0.11
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: 0.1.3+3
  # https://pub.dev/packages/flutter_udid
  flutter_udid: 1.0.1
  # https://pub.dev/packages/wakelock
  wakelock: 0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  # https://pub.dev/packages/screenshots
  screenshots: ^2.1.1
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
