default_platform(:android)

platform :android do

  desc "Run Tests"
  lane :test do
    Dir.chdir("../../") do
      sh("flutter", "pub", "get")
      sh("flutter", "pub", "run", "flutter_launcher_icons:main")
#      sh("screenshots")
      sh("flutter", "clean")
      sh('flutter', 'build', 'appbundle')
    end
  end

  desc "Submit a new build to Internal Track on Play"
  lane :internal do
    ensure_git_branch(branch: 'master')

    ensure_git_status_clean

    Dir.chdir("../../") do
      sh("flutter", "pub", "get")
      sh("flutter", "pub", "run", "flutter_launcher_icons:main")
#      sh("screenshots")
      sh("flutter", "clean")
      sh('flutter', 'build', 'appbundle')
    end

    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      skip_upload_aab: false,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      deactivate_on_promote: false,
      rollout: '1.0'
    )
  end

end
